### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by Christophvh** [danielgormly/statamic-nginx-docker#3]
When i try to do these steps i get a 403 forbidden from nginx

**Comment by danielgormly** [comment]
I've just tried pulling everything and building from scratch. The project still seems to work.
Do you definitely have a directory structure that looks like:
```
- docker-compose.yml
- readme.md
- statamic
--- installer.php
```
Check that you have execute permissions on the statamic folder i.e. `chmod 700 statamic`

**Comment by Christophvh** [comment]
yes, I think the problem is related to my nginx config ? do I have to change anything in the provided nginx?

**Comment by danielgormly** [comment]
Can you print out your `ls -lha` on the project directory and statamic directory? Nginx config should be good but it may not be able to read or execute the php files or access certain directories.

**Comment by Christophvh** [comment]
I did a chmod 700 on the statamic folder still 403.

Result of ls -lha on the project root:
<img width="333" alt="screen shot 2018-09-27 at 09 46 53" src="https://user-images.githubusercontent.com/9588070/46130751-51bc8080-c23a-11e8-8636-c3b32fa29c56.png">

**Comment by danielgormly** [comment]
Sorry man, I know this is really late, but you actually have to extract statamic files into `<repo-root>/statamic/`, not directly into the root folder of the repo.

**Comment by danielgormly** [comment]
I may build this into the build process, just couldn't find a static statamic download link when I was building it.
