### ISSUE TITLE
Run Statamic Docker Container on Windows?

### ISSUE THREAD

**Issue by combiths** [danielgormly/statamic-nginx-docker#4]
I tried to run the docker-compose command on a Windows machine and I'm seeing the following error. Looks like the script only supports flavors of Linux?

checking for pkg-config... /usr/bin/pkg-config
checking for libzip... not found
configure: error: Please reinstall the libzip distribution
ERROR: Service 'fpm' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y     libjpeg62-turbo-dev     libpng-dev     zlib1g-dev   && rm -rf /var/lib/apt/lists/*   && docker-php-ext-configure gd --with-jpeg-dir=/usr/include/   && docker-php-ext-install -j$(nproc) gd   && docker-php-ext-install exif   && docker-php-ext-install zip' returned a non-zero code: 1

**Comment by danielgormly** [comment]
I will take a look in the next day or so from my windows partition, but I don't see why it shouldn't work from a Windows machine running a VM/hypervisor. I'll see if I can recreate the error first on my Mac, then on Windows.

**Comment by danielgormly** [comment]
Hi I guess there was a change with the packages or the latest php-7:fpm image - I haven't pinned that down beyond the major version. It didn't run on my Mac either. I've added `libzip-dev` to the installation and it now runs. Could you please pull the latest and try again? Thanks

**Comment by combiths** [comment]
Confirmed it's working now. Thanks!
