### ISSUE TITLE
`configure: error: unrecognized options: --with-jpeg-dir`

### ISSUE THREAD

**Issue by vladislavbogomolov** [danielgormly/statamic-nginx-docker#5]
On docker compose run  
`configure: error: unrecognized options: --with-jpeg-dir`

**Comment by sascha-schieferdecker** [comment]
I can confirm the issue

**Comment by danielgormly** [comment]
Hi I was overseas when the issue came up, I'll take a look later today.

**Comment by wakeuphate** [comment]
Hey @vladislavbogomolov & @sascha-schieferdecker , just in-case you aren't pinged by the pull request, this can be fixed in https://github.com/danielgormly/statamic-nginx-docker/pull/6 if you need a solution right away.

**Comment by danielgormly** [comment]
Thanks! I'll just leave it open so other people can confirm the solution. Haven't personally tested. I should really pin the versions...

**Comment by sascha-schieferdecker** [comment]
I think you can close this issue. The fix is working, the build runs fine. Thanks @wakeuphate

**Comment by danielgormly** [comment]
Great thanks @sascha-schieferdecker
